/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Excuses by @aaronbassett  --  http://www.codingexcuses.com": "Excuses by @aaronbassett  --  http://www.codingexcuses.com",
    "Made by Ryan Batchelder": "Made by Ryan Batchelder",
    "test": "Excuse goes here",
    "Widget by Ryan Batchelder": "Widget by Ryan Batchelder"
};

